name: deploy-frontend-to-stage 
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  deploy-to-stage:
    runs-on: ubuntu-latest
    steps: 
      - name: Check for version chnage
        id: version_changed
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          
      - name: hello-world
        run: echo "Hello World"


