name: deploy-frontend-to-stage 
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  any-job:
    runs-on: ubuntu-latest
    steps: 
      - name: any-step
        run: echo "Hello World"
